ERROR conda.cli.main_run:execute(32): Subprocess for 'conda run ['python', 'scripts/save_embeddings.py', '--input', '/lustre/groups/ml01/workspace/ignacio.ibarra/theislab/retinal_scRNAseq_integration/data/integration_march_2021/output/retinal_all_cells_Chenfixed+Hackney_batch_donor_dataset_cell.type/integration/unscaled/HVG.3K/scvi_E50.h5ad', '--outfile', '/lustre/groups/ml01/workspace/ignacio.ibarra/theislab/retinal_scRNAseq_integration/data/integration_march_2021/output/retinal_all_cells_Chenfixed+Hackney_batch_donor_dataset_cell.type/embeddings/unscaled/HVG.3K/scvi_E50_embed.csv', '--method', 'scvi_E50', '--batch_key', 'batch_donor_dataset', '--label_key', 'cell.type', '--result', 'embed']' command failed.  (See above for error)
python: can't open file 'scripts/save_embeddings.py': [Errno 2] No such file or directory

